import { Geist, Geist_Mono, Montserrat, K2D } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
	return (
		<html lang="en" suppressHydrationWarning>
			<head />
			<body>
				<ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
					<div>{children}</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
