import { Geist, Geist_Mono, Montserrat, K2D } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import Navbar from "@/components/Navbar";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function MainLayout({ children }) {
	return (
		<ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
			<Navbar />
			<div className="pt-24">{children}</div>
		</ThemeProvider>
	);
}
